name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Display the path
      run: |
        echo $(pwd)
        echo $(ls -l)
      shell: bash

    - name: Install and Update platformio
      run: |
        pip install -U platformio
        platformio update
        
    - name: Run a paltformio
      run: platformio run
